### PR TITLE
feat: add a search feature

### PR DESCRIPTION
**Pull request by khizarkhan345**

### CODE REVIEW

**Comment by Lawangin** [comment]
The search bar tech should be black. Currently, it is light gray. 
image

**Comment by Lawangin** [comment]
The search doesn't work when I press `Enter`. You will likely need to create a form or a listener for the `enter key` from the input component.

**Comment by khizarkhan345** [comment]
It was working in my machine. However, when we scroll down, the search get
disabled. I am going to fix it soon.

**Comment by Lawangin** [comment]
Yeah we just need to run `handleFilterData()` and increment the page number in the pagination url when we use `useInfiniteScroll()` with a search term present.

**Comment by khizarkhan345** [comment]
I added the about us page as well. I will need your help in implementing the infinite scroll when we search a job.

**Pull request merged**
